---
- hosts: all
  become: true
  roles:
  - all
  - role: ericsysmin.chrony
    chrony_config_server:
      - mickey.lss.emc.com

- hosts: master
  become: true
  roles:
  - master

- hosts: manager
  become: true
  roles:
  - manager
