---
- hosts: all
  become: true
  vars_files:
    - ./vars.yml
  roles:
  - all
  #  - role: ericsysmin.chrony
  #  chrony_config_server:
  #    - "{{ ntp_server }}"

- hosts: master
  become: true
  roles:
  - master

- hosts: manager
  become: true
  roles:
  - manager
