---
- name: "YUM update"
  yum:
    name: '*'
    state: latest
  tags:
    - swarm

- name: "Upgrade Kernel"
  yum:
    name: http://mirror.rc.usf.edu/compute_lock/elrepo/kernel/el7/x86_64/RPMS/kernel-ml-4.10.5-1.el7.elrepo.x86_64.rpm
    state: present
    validate_certs: no
  tags:
    - swarm

- name: "rebuild grub"
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  become: yes
  tags:
    - swarm

- name: "Set Default Kernel to 5.x in grub"
  command: grub2-set-default 0
  become: yes
  tags:
    - swarm

- name: "Reboot server"
  reboot:
    reboot_timeout: 600
  tags:
    - swarm
