---
- name: "YUM update"
  yum:
    name: '*'
    state: latest
  tags:
    - vxflex

- name: "Upgrade Kernel"
  yum:
    name: https://object.bluehairfreak.com/vxflexos/kernel-ml-4.10.5-1.el7.elrepo.x86_64.rpm
    state: present
    become: yes
  tags:
    - vxflex

- name: "rebuild grub"
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  become: yes
  tags:
    - vxflex

- name: "Set Default Kernel to 5.x in grub"
  command: grub2-set-default 0
  become: yes
  tags:
    - vxflex

- name: "Reboot server"
  reboot:
    reboot_timeout: 600
  tags:
    - vxflex
