- name: "Installing Basic Tools"
  package: pkg={{ item }} state=installed
  with_items:
  - git
  - vim
  - numactl
  - sysfsutils
  - unzip
  - wget
  - net-tools
  - yum-utils
  - lvm2
  tags:
    - swarm

- debug:
    var: ansible_kernel
  tags:
    - kernel

- name: "Upgrade Kernel to 5.x"
  include_tasks: centos_kernel_upgrade.yml
  when: ansible_kernel is version('3','<=')
  tags:
    - kernel

- name: set timezone to UTC
  timezone:
    name: UTC
    hwclock: UTC
  tags:
    - swarm

- name: "Disable Centos FireWall Service"
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_facts['distribution'] == "Centos"
  tags:
    - swarm

- name: "Disable Ubuntu FireWall Service"
  systemd:
    name: ufw
    state: stopped
    enabled: no
  when: ansible_facts['distribution'] == "Ubuntu"
  tags:
    - swarm

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  when: ansible_facts['distribution'] == "Centos"
  tags:
    - swarm

- apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"
  tags:
    - swarm

- name: "Install Docker-CE"
  package:
    name: docker-ce
    state: present
  tags:
    - swarm

- name: Creates directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  tags:
    - swarm

- name: Copies override.conf for enabling Docker API
  copy:
    src: ./files/override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf
  tags:
    - swarm

- name: "Make sure the service starts at boot and is currently started"
  systemd:
    name: docker
    daemon_reload: yes
    state: started
    enabled: yes
  tags:
    - swarm

- name: Copies the scaleio client to /tmp
  copy:
    src: ./files/EMC-ScaleIO-sdc-{{vxflex_version}}.el7.x86_64.rpm
    dest: /tmp/EMC-ScaleIO-sdc-{{vxflex_version}}.el7.x86_64.rpm
  tags:
    - vxflex

- name: Install SDC
  yum:
    name: /tmp/EMC-ScaleIO-sdc-{{vxflex_version}}.el7.x86_64.rpm
    state: present
  environment:
    MDM_IP: "{{ vxflex_master_mdm_ip | join(',') }},{{ vxflex_standby_mdm_ip | join(',')}}"
  tags:
    - vxflex

- name: Adding user root
  user: name=root
        group=docker

- name: "Find out if rexray is already installed"
  shell: docker plugin ls | grep rexray
  register: REXRAY
  failed_when: "REXRAY.rc == 2"
  tags:
    - vxflex

- name: "Install RexRay if it is not already installed"
  shell: echo "y" | docker plugin install rexray/scaleio SCALEIO_ENDPOINT=https://{{ vxflex_gateway_ip }}:{{ vxflex_gateway_https_port }}/api SCALEIO_USERNAME={{ vxflex_gateway_username }} SCALEIO_PASSWORD={{ vxflex_gateway_pw }} SCALEIO_SYSTEMNAME={{ vxflex_system_name }} SCALEIO_PROTECTIONDOMAINNAME={{ vxflex_protection_domain_name }} SCALEIO_STORAGEPOOLNAME={{vxflex_storage_pool_name}} REXRAY_PREEMPT=true REXRAY_LOGLEVEL={{rexray_log_level}}
  when: REXRAY.rc == 1
  tags:
    - vxflex
