- name: "Installing Basic Tools"
  package: pkg={{ item }} state=installed
  with_items:
  - git
  - vim
  - libaio
  - numactl
  - sysfsutils
  - unzip
  - wget
  - net-tools
  - yum-utils
  - device-mapper-persistent-data
  - lvm2

- name: set timezone to UTC
  timezone:
    name: UTC
    hwclock: UTC

- name: "Disable FireWall Service"
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: "Install Docker-CE"
  package:
    name: docker-ce
    state: present

- name: Creates directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Copies override.conf for enabling Docker API
  copy:
    src: ./files/override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf

- name: "Make sure the service starts at boot and is currently started"
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Copies the scaleio client to /tmp
  copy:
    src: ./files/EMC-ScaleIO-sdc-2.6-10000.123.el7.x86_64.rpm
    dest: /tmp/EMC-ScaleIO-sdc-2.6-10000.123.el7.x86_64.rpm

- name: Install SDC
  yum:
    name: /tmp/EMC-ScaleIO-sdc-2.6-10000.123.el7.x86_64.rpm
    state: present
  environment:
    MDM_IP: 192.168.10.201,192.168.11.201,192.168.10.202,192.168.11.202

- name: Adding user root
  user: name=root
        group=docker

- name: "Find out if rexray is already installed"
  shell: docker plugin ls | grep rexray
  register: REXRAY
  failed_when: "REXRAY.rc == 2"

- name: "Install RexRay if it is not already installed"
  shell: echo "y" | docker plugin install rexray/scaleio SCALEIO_ENDPOINT=https://10.237.198.170/api SCALEIO_USERNAME=admin SCALEIO_PASSWORD=Password#1 SCALEIO_SYSTEMID=07e2bf1f7667b4e9 SCALEIO_PROTECTIONDOMAINNAME=pd1 SCALEIO_STORAGEPOOLNAME=sp1 REXRAY_PREEMPT=true REXRAY_LOGLEVEL=debug
  when: REXRAY.rc == 1
