- name: "Installing Basic Tools"
  package: pkg={{ item }} state=installed
  with_items:
  - git
  - vim
  - libaio
  - numactl
  - sysfsutils
  - unzip
  - wget
  - net-tools
  - yum-utils
  - device-mapper-persistent-data
  - lvm2

- name: set timezone to UTC
  timezone:
    name: UTC
    hwclock: UTC

- name: "Disable FireWall Service"
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: "Install Docker-CE"
  package:
    name: docker-ce
    state: present

- name: Creates directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Copies override.conf for enabling Docker API
  copy:
    src: ./files/override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf

- name: "Make sure the service starts at boot and is currently started"
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Copies the scaleio client to /tmp
  copy:
    src: ./files/EMC-ScaleIO-sdc-{{vxflex_version}}.el7.x86_64.rpm
    dest: /tmp/EMC-ScaleIO-sdc-{{vxflex_version}}.el7.x86_64.rpm

- name: Install SDC
  yum:
    name: /tmp/EMC-ScaleIO-sdc-{{vxflex_version}}.el7.x86_64.rpm
    state: present
  environment:
    MDM_IP: "{{ vxflex_mdm_ip }}"

- name: Adding user root
  user: name=root
        group=docker

- name: "Find out if rexray is already installed"
  shell: docker plugin ls | grep rexray
  register: REXRAY
  failed_when: "REXRAY.rc == 2"

- name: "Install RexRay if it is not already installed"
  shell: echo "y" | docker plugin install rexray/scaleio SCALEIO_ENDPOINT=https://{{ vxflex_gateway_ip}}/api SCALEIO_USERNAME={{ vxflex_gateway_username }} SCALEIO_PASSWORD={{ vxflex_gateway_pw }} SCALEIO_SYSTEMID={{ vxflex_system_id }} SCALEIO_PROTECTIONDOMAINNAME={{ vxflex_protection_domain_name }} SCALEIO_STORAGEPOOLNAME={{vxflex_storage_pool_name}} REXRAY_PREEMPT=true REXRAY_LOGLEVEL={{rexray_log_level}}
  when: REXRAY.rc == 1
