---
- name: "Allow Ports in Ubuntu for Docker Swarm"
  ufw:
    state: enabled
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
  - '2377'
  - '7946'
  - '8080'
  - '50'
  - '80'
  - '443'
  - '2375'
  - '2376'
  - '22'
  tags:
    - firewall

- name: "Allow Ports in Ubuntu for Docker Swarm"
  ufw:
    state: enabled
    rule: allow
    port: "{{ item }}"
    proto: udp
  with_items:
  - 7946
  - 4789
  tags:
    - firewall

- name: "Restar the Firewalld service"
  service:
    name: ufw
    state: restarted
