- name: "Installing Basic Tools"
  package: pkg={{ item }} state=installed
  with_items:
  - git
  - vim
  - libaio
  - numactl
  - sysfsutils
  - unzip
  - wget
  - net-tools
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
  - ntp

- name: "Disable FireWall Service"
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: "Start and Enable NTPD"
  systemd:
    name: ntpd
    state: started
    enabled: yes

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: "Install Docker-CE"
  package:
    name: docker-ce
    state: present

- name: Creates directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Copies override.conf for enabling Docker API
  copy:
    src: ./override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf

- name: Adding user root
  user: name=root
        group=docker

- name: "Make sure the service starts at boot and is currently started"
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: "Join the Swarm Cluster"
  shell: "{{ hostvars['MASTER_TOKEN_HOLDER']['token'] }}"
  ignore_errors: yes

- debug:
    msg: "{{ hostvars['MASTER_TOKEN_HOLDER']['token'] }}"
