- name: "See if node is already in a swarm"
  shell: "docker info | grep Swarm | sed 's/Swarm: //g' | tr -d '[:space:]'"
  register: swarm_state
  
- name: "Swarm output"
  debug:
    var: swarm_state
    
- name: "Initialize docker swarm instance and caputure ID"
  shell: "docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}"
  register: docker_id
  when: swarm_state.stdout == " inactive"

- name: "Display docker swarm token ID"
  shell: "docker swarm join-token manager | awk '{if(NR>1)print}'"
  register: docker_id_number

- name: "Add Token and to dummy host, used to pass variable to other playbook"
  add_host:
    name:   "MASTER_TOKEN_HOLDER"
    token:  "{{ docker_id_number.stdout }}"

- name: "Master Swarm IP"
  debug:
    var: ansible_default_ipv4.address
